name: chat_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.0
  flutter_riverpod: ^2.0.0
  http: ^0.13.4 
  flutter_secure_storage: ^5.0.0
  crypto: ^3.0.1
  image_picker: ^1.0.4

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: interFontFamily
      fonts:
        - asset: lib/fonts/Inter-Black.ttf
        - asset: lib/fonts/Inter-Bold.ttf
        - asset: lib/fonts/Inter-Light.ttf
        - asset: lib/fonts/Inter-Regular.ttf
        - asset: lib/fonts/Inter-Thin.ttf